<?php
require_once AgaviToolkit::expandDirectives('%core.module_dir%/Core/lib/config/PageConfigHandler.class.php');
class Core_PageConfigHandlerTest extends AgaviUnitTestCase
{	
	public function testExecute()
	{
		AgaviConfigCache::addConfigHandlersFile(AgaviConfig::get('core.testing_dir') . '/fixtures/config/core_pagesconfighandler_config_handlers.xml');
		
		$compiled = <<<'EOT'
<?php

// This is a compiled Agavi configuration file
// Compiled from: (unknown)
// Generated by: Core_PageConfigHandler
// Date: 0000-00-00T00:00:00+0000

switch($name){
case '/':
$this->filePath = '%core.testing_dir%/fixtures/pages/main.tpl';
$this->layout = NULL;
$this->renderer = NULL;
$this->responseAttributes = array (
  'stylesheets' => 
  array (
    0 => 'css/main.css',
  ),
);
break;
case '/other':
$this->filePath = '%core.testing_dir%/fixtures/pages/other.tpl';
$this->layout = 'simple';
$this->renderer = NULL;
$this->responseAttributes = NULL;
break;
case '/bbs/logs':
$this->filePath = '%core.testing_dir%/fixtures/pages/bbs-logs.php';
$this->layout = NULL;
$this->renderer = 'php';
$this->responseAttributes = NULL;
break;
default:
return false;
}
return true;

?>
EOT;
		$compiled = str_replace('\\', '\\\\', AgaviToolkit::expandDirectives($compiled));
		$this->assertEquals($compiled, preg_replace('#^// Date: .*$#m', '// Date: 0000-00-00T00:00:00+0000',
				file_get_contents(AgaviConfigCache::checkConfig(AgaviToolkit::expandDirectives('%core.testing_dir%/fixtures/config/pages.xml')))));
	}
	
	protected function tearDown()
	{
		AgaviConfigCache::clear();
	}
}
?>
